### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by Farfi55** [denogio/pop-launcher-bitwarden#2]
I'm not an expert, so I apologize if this is some trivial mistake or missing packages on my part.

after having installed the requirements, I'm unable to install the repo

I've also configured rbw and it's working correctly

```
> git clone https://github.com/denogio/pop-launcher-bitwarden.git
> cd pop-launcher-bitwarden 
> make install
make: Nothing to be done for 'install'.
```

the Makefile clearly contains an 'install' section
how can I fix this?

**Comment by denogio** [comment]
Thank you for your report. That is an error from my side. My editor did change the tabs in Makefile to spaces. I have corrected this. You should be able to clone again and install.

**Comment by Farfi55** [comment]
yes, new version fixed it and works great, this issue can be closed for me :)
